# Define hooks for code formations


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx
        sudo apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
